"""
gen_exp_lut.py
Offline table generator for the gbm_logspace.v exp() lookup table.
"""
import numpy as np
import math

# Configuration
N_ENTRIES     = 8192
L_MIN         = 0.0
L_MAX         = 5.545
PRICE_FRAC    = 24
L_FRAC        = 24
PRICE_MAX_INT = (256 << PRICE_FRAC) - 1

# Compute LUT entries
L_step   = (L_MAX - L_MIN) / N_ENTRIES
L_values = np.array([L_MIN + i * L_step for i in range(N_ENTRIES)])
exp_values = np.exp(L_values)
exp_q824 = np.array([
    min(int(round(e * (1 << PRICE_FRAC))), PRICE_MAX_INT)
    for e in exp_values
], dtype=np.int64)

L_MIN_FIXED  = int(round(L_MIN  * (1 << L_FRAC)))
L_STEP_FIXED = int(round(L_step * (1 << L_FRAC)))

# Reciprocal multiplier for hardware address calculation
shift = 48
while (1 << shift) // L_STEP_FIXED >= (1 << 32):
    shift -= 1
L_STEP_RECIP = int(round((1 << shift) / L_STEP_FIXED))

print(f"LUT configuration:")
print(f"  N_ENTRIES    = {N_ENTRIES}")
print(f"  L range      = [{L_MIN:.3f}, {L_MAX:.3f}]")
print(f"  L_step       = {L_step:.6f}")
print(f"  L_MIN_FIXED  = {L_MIN_FIXED} (32'h{L_MIN_FIXED & 0xFFFFFFFF:08X})")
print(f"  L_STEP_FIXED = {L_STEP_FIXED} (32'h{L_STEP_FIXED:08X})")
print(f"  L_STEP_RECIP = {L_STEP_RECIP} (32'h{L_STEP_RECIP:08X})")
print(f"  VERILOG SHIFT AMOUNT = {shift}")
print(f"  VERILOG EXTRACTION   = addr_full_wire[{shift+12}:{shift}]")
print(f"  Price range  = [{exp_values[0]:.4f}, {exp_values[-1]:.2f}]")
print(f"  exp_q824 spot checks: [0]={exp_q824[0]}, [4095]={exp_q824[4095]}, [8191]={exp_q824[8191]}")

# Quantization error verification
max_abs_err = 0.0
max_rel_err = 0.0
for i in range(N_ENTRIES):
    real_val    = exp_q824[i] / (1 << PRICE_FRAC)
    clamped_val = min(exp_values[i], PRICE_MAX_INT / (1 << PRICE_FRAC))
    abs_err     = abs(real_val - clamped_val)
    rel_err     = abs_err / clamped_val
    max_abs_err = max(max_abs_err, abs_err)
    max_rel_err = max(max_rel_err, rel_err)

print(f"\nQuantization error:")
print(f"  Max absolute error: {max_abs_err:.6e}")
print(f"  Max relative error: {max_rel_err*100:.4f}%")

# Generate MIF file
mif_filename = "exp_lut.mif"
with open(mif_filename, "w", encoding="utf-8") as f:
    f.write(f"-- exp() LUT for gbm_logspace.v\n")
    f.write(f"-- Generated by gen_exp_lut.py\n")
    f.write(f"-- L range: [{L_MIN}, {L_MAX}], N={N_ENTRIES}, Q8.24 output\n")
    f.write(f"WIDTH = 32;\n")
    f.write(f"DEPTH = {N_ENTRIES};\n")
    f.write(f"ADDRESS_RADIX = UNS;\n")
    f.write(f"DATA_RADIX = UNS;\n")
    f.write(f"CONTENT BEGIN\n")
    for i, val in enumerate(exp_q824):
        f.write(f"    {i} : {int(val)};\n")
    f.write(f"END;\n")
print(f"\nWrote {mif_filename}")

# Generate behavioral Verilog header
vh_filename = "exp_lut.vh"
with open(vh_filename, "w", encoding="utf-8") as f:
    f.write("// exp_lut.vh - Behavioral exp() LUT for ModelSim\n")
    f.write("// Generated by gen_exp_lut.py\n")
    f.write(f"// L range [{L_MIN:.3f}, {L_MAX:.3f}], step={L_step:.6f}\n\n")
    f.write("function [31:0] exp_lut_lookup;\n")
    f.write("    input [12:0] addr;\n")
    f.write("    begin\n")
    f.write("        case (addr)\n")
    for i, val in enumerate(exp_q824):
        f.write(f"            13'd{i:<4d}: exp_lut_lookup = 32'h{int(val):08X};\n")
    f.write("            default: exp_lut_lookup = 32'h00000000;\n")
    f.write("        endcase\n")
    f.write("    end\n")
    f.write("endfunction\n")
print(f"Wrote {vh_filename}")

# Generate Python golden model constants
py_filename = "exp_lut_golden.py"
with open(py_filename, "w", encoding="utf-8") as f:
    f.write('"""\nGenerated by gen_exp_lut.py - Quantized exp() LUT constants\n"""\n\n')
    f.write(f'N_ENTRIES    = {N_ENTRIES}\n')
    f.write(f'L_MIN        = {L_MIN}\n')
    f.write(f'L_MAX        = {L_MAX}\n')
    f.write(f'L_STEP       = {L_step!r}\n')
    f.write(f'L_MIN_FIXED  = {L_MIN_FIXED}\n')
    f.write(f'L_STEP_FIXED = {L_STEP_FIXED}\n')
    f.write(f'L_STEP_RECIP = {L_STEP_RECIP}\n')
    f.write(f'L_STEP_SHIFT = {shift}\n')
    f.write(f'PRICE_FRAC   = {PRICE_FRAC}\n')
    f.write(f'L_FRAC       = {L_FRAC}\n\n')
    f.write('EXP_LUT = [\n')
    for i, val in enumerate(exp_q824):
        f.write(f'    {int(val)},  # L={L_values[i]:.4f} -> exp={exp_values[i]:.4f}\n')
    f.write(']\n\n')
    f.write('def exp_lut_lookup(addr):\n')
    f.write('    if 0 <= addr < N_ENTRIES:\n')
    f.write('        return EXP_LUT[addr]\n')
    f.write('    return 0\n\n')
    f.write('def l_to_price(L_fixed):\n')
    f.write('    """\n    Convert Q8.24 log-price integer to Q8.24 price integer.\n')
    f.write('    Mirrors gbm_logspace.v hardware implementation.\n    """\n')
    f.write('    offset = L_fixed - L_MIN_FIXED\n')
    f.write('    if offset < 0:\n')
    f.write('        return exp_lut_lookup(0)\n')
    f.write(f'    addr = (offset * L_STEP_RECIP) >> {shift}\n')
    f.write('    if addr >= N_ENTRIES:\n')
    f.write('        return exp_lut_lookup(N_ENTRIES - 1)\n')
    f.write('    return exp_lut_lookup(int(addr))\n')
print(f"Wrote {py_filename}")