#!/usr/bin/env python3
"""
gen_ziggurat_tables.py
Precomputes the 256-layer Ziggurat tables for the standard normal distribution
using the Marsaglia & Tsang (2000) construction.

Outputs:
    ziggurat_tables.mif   - Quartus M10K ROM initialization file
    ziggurat_tables.py    - Python module with table constants (for golden model)
    ziggurat_tables.vh    - Verilog header with table as localparams (for sim)

Q-format: Q4.12 fixed-point (16-bit signed)
  - x values in [0, ~3.7], fits comfortably in Q4.12
  - y values in [0, 1.0],  fits comfortably in Q4.12
  - Scale factor: 4096 (2^12)

ROM layout (512 x 16-bit words, two banks):
  Address [8:0]:
    addr[8]   = 0 -> x_table[addr[7:0]]
    addr[8]   = 1 -> y_table[addr[7:0]]
"""

import numpy as np
import math

# ---------------------------------------------------------------------------
# Ziggurat construction: Marsaglia & Tsang 2000
# N = 256 layers, for N(0,1)
# ---------------------------------------------------------------------------

N = 256
Q_SCALE = 4096      # Q4.12
Q_BITS  = 16

def norm_pdf(x):
    return math.exp(-0.5 * x * x) / math.sqrt(2 * math.pi)

def norm_pdf_unnorm(x):
    """Unnormalized: f(x) = exp(-0.5*x^2).  Used in Ziggurat construction."""
    return math.exp(-0.5 * x * x)

def build_ziggurat_tables(n=256):
    from scipy.optimize import brentq
    target_area = math.sqrt(math.pi / 2.0)
    
    def equations(r):
        tail = math.sqrt(math.pi / 2.0) * math.erfc(r / math.sqrt(2.0))
        return (r * norm_pdf_unnorm(r) + tail) - target_area / n
        
    r = brentq(equations, 2.0, 4.0)
    v = r * norm_pdf_unnorm(r) + math.sqrt(math.pi / 2.0) * math.erfc(r / math.sqrt(2.0))

    x = [0.0] * n
    y = [0.0] * n

    # Layer 255 is the bottom layer (includes bounding box width)
    x[n-1] = v / norm_pdf_unnorm(r)
    x[n-2] = r
    y[n-1] = norm_pdf_unnorm(r)
    y[n-2] = norm_pdf_unnorm(r)

    # Build upwards to the peak
    for i in range(n-3, -1, -1):
        x[i] = math.sqrt(-2.0 * math.log(v / x[i+1] + y[i+1]))
        y[i] = norm_pdf_unnorm(x[i])
        
    # Force absolute peak
    x[0] = 0.0
    y[0] = 1.0

    return x, y, r, v


def to_q412(val, saturate=True):
    """Convert float to Q4.12 signed 16-bit integer."""
    scaled = round(val * Q_SCALE)
    if saturate:
        scaled = max(-32768, min(32767, scaled))
    return scaled & 0xFFFF  # as unsigned 16-bit for MIF


def write_mif(x_table, y_table, filename="ziggurat_tables.mif"):
    """
    Write Quartus MIF file for a 512x16 ROM.
    Lower 256 words = x_table, upper 256 words = y_table.
    """
    n = len(x_table)
    assert len(y_table) == n == 256

    lines = []
    lines.append("-- Ziggurat N(0,1) lookup tables")
    lines.append("-- Generated by gen_ziggurat_tables.py")
    lines.append("-- Format: Q4.12 signed fixed-point (stored as unsigned hex)")
    lines.append("-- Addresses 0x000..0x0FF: x_table[0..255]")
    lines.append("-- Addresses 0x100..0x1FF: y_table[0..255]")
    lines.append(f"WIDTH=16;")
    lines.append(f"DEPTH=512;")
    lines.append(f"ADDRESS_RADIX=HEX;")
    lines.append(f"DATA_RADIX=HEX;")
    lines.append(f"CONTENT BEGIN")

    for i in range(n):
        xv = to_q412(x_table[i])
        lines.append(f"\t{i:03X} : {xv:04X};  -- x[{i}] = {x_table[i]:.6f}")

    for i in range(n):
        yv = to_q412(y_table[i])
        lines.append(f"\t{i+n:03X} : {yv:04X};  -- y[{i}] = {y_table[i]:.6f}")

    lines.append("END;")

    with open(filename, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {filename}  ({2*n} entries, 512x16 ROM)")


def write_verilog_header(x_table, y_table, filename="ziggurat_tables.vh"):
    """
    Write a Verilog include file with the tables as a ROM initializer.
    Used in simulation (non-synthesis) via $readmemh or case statement.
    For synthesis: use the .mif file with M10K.
    """
    n = len(x_table)
    lines = []
    lines.append("// ziggurat_tables.vh")
    lines.append("// Auto-generated by gen_ziggurat_tables.py")
    lines.append("// Q4.12 fixed-point Ziggurat tables for N(0,1), 256 layers")
    lines.append("// Include in ziggurat_gaussian.v for behavioral simulation")
    lines.append("// For synthesis: use ziggurat_tables.mif with M10K ROM")
    lines.append("")
    lines.append("// x_table: layer right-edge x-coordinates")
    lines.append("// y_table: layer y-coordinates (= f(x[i]) = exp(-0.5*x[i]^2))")
    lines.append("")

    # x table as a task/function for behavioral sim
    lines.append("// Behavioral ROM function - replace with M10K in synthesis")
    lines.append("function [15:0] zig_x_rom;")
    lines.append("    input [7:0] idx;")
    lines.append("    case (idx)")
    for i in range(n):
        xv = to_q412(x_table[i])
        lines.append(f"        8'd{i}: zig_x_rom = 16'h{xv:04X}; // {x_table[i]:.6f}")
    lines.append("        default: zig_x_rom = 16'h0000;")
    lines.append("    endcase")
    lines.append("endfunction")
    lines.append("")

    lines.append("function [15:0] zig_y_rom;")
    lines.append("    input [7:0] idx;")
    lines.append("    case (idx)")
    for i in range(n):
        yv = to_q412(y_table[i])
        lines.append(f"        8'd{i}: zig_y_rom = 16'h{yv:04X}; // {y_table[i]:.6f}")
    lines.append("        default: zig_y_rom = 16'h0000;")
    lines.append("    endcase")
    lines.append("endfunction")

    with open(filename, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {filename}  (Verilog behavioral ROM functions)")


def write_python_module(x_table, y_table, r, v, filename="ziggurat_tables_golden.py"):
    """Write Python module for use in cross_check.py golden model."""
    n = len(x_table)
    lines = []
    lines.append('"""')
    lines.append('ziggurat_tables_golden.py')
    lines.append('Auto-generated Ziggurat tables for N(0,1) golden model.')
    lines.append('Q4.12 quantized versions match the hardware ROM exactly.')
    lines.append('"""')
    lines.append(f"N_LAYERS = {n}")
    lines.append(f"TAIL_START_R = {r:.10f}  # x[N-1], tail begins here")
    lines.append(f"LAYER_VOLUME_V = {v:.10f}  # per-layer area")
    lines.append(f"Q_SCALE = {Q_SCALE}  # Q4.12")
    lines.append("")

    x_q = [to_q412(xi) for xi in x_table]
    y_q = [to_q412(yi) for yi in y_table]

    # Store as quantized (matching hardware) and as float
    lines.append(f"X_TABLE_RAW = {x_q}")
    lines.append(f"Y_TABLE_RAW = {y_q}")
    lines.append("")
    lines.append(f"X_TABLE = [v/Q_SCALE for v in X_TABLE_RAW]")
    lines.append(f"Y_TABLE = [v/Q_SCALE for v in Y_TABLE_RAW]")

    with open(filename, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {filename}  (Python golden model tables)")


if __name__ == "__main__":
    print("Building Ziggurat N(0,1) tables (N=256, Q4.12)...")
    x_table, y_table, r, v = build_ziggurat_tables(N)

    print(f"  Tail start r = {r:.6f}")
    print(f"  Layer volume v = {v:.8f}")
    print(f"  x[0]   = {x_table[0]:.6f}  (should be 0.0)")
    print(f"  x[255] = {x_table[255]:.6f}  (should be ~{r:.4f})")
    print(f"  y[0]   = {y_table[0]:.6f}  (should be 1.0)")
    print(f"  y[255] = {y_table[255]:.6f}  (should be ~{math.exp(-0.5*r*r):.4f})")

    # Verify: all rectangles should have equal area
    areas = []
    for i in range(1, N):
        area = (x_table[i] - x_table[i-1]) * y_table[i]
        areas.append(area)
    print(f"  Layer area uniformity: min={min(areas):.6f}, max={max(areas):.6f}, std={np.std(areas):.2e}")

    write_mif(x_table, y_table, "ziggurat_tables.mif")
    write_verilog_header(x_table, y_table, "ziggurat_tables.vh")
    write_python_module(x_table, y_table, r, v, "ziggurat_tables_golden.py")

    print("\nDone. Files generated:")
    print("  ziggurat_tables.mif           -> load into Quartus M10K ROM")
    print("  ziggurat_tables.vh            -> include in Verilog for ModelSim")
    print("  ziggurat_tables_golden.py     -> import in cross_check.py")