"""Generates the exp() lookup table consumed by gbm_logspace.v in three companion formats.

Emits the Q8.24 exp(L) table as a Quartus MIF for M10K ROM initialization, a behavioral Verilog include with a
case-statement lookup function for ModelSim simulation, and a Python module that the gbm_golden_model imports to mirror
the hardware lookup. The L axis is sampled uniformly between log_price_min and log_price_max so the address-from-L
mapping reduces to a multiply by a precomputed reciprocal followed by a right shift, matching the synthesis path
bit-for-bit.
"""

from pathlib import Path

import numpy as np
from numpy.typing import NDArray

_ENTRY_COUNT: int = 8192
_LOG_PRICE_MIN: float = 0.0
_LOG_PRICE_MAX: float = 5.545
_PRICE_FRAC: int = 24
_LOG_PRICE_FRAC: int = 24
_PRICE_MAX_INT: int = (256 << _PRICE_FRAC) - 1
_RECIPROCAL_SHIFT_START: int = 48
_RECIPROCAL_SHIFT_LIMIT: int = 1 << 32
_VERILOG_ADDRESS_LOWER_OFFSET: int = 12

_SCRIPT_DIRECTORY: Path = Path(__file__).resolve().parent
_LUT_DIRECTORY: Path = _SCRIPT_DIRECTORY.parent / "rtl" / "lut"
_MIF_OUTPUT_PATH: Path = _LUT_DIRECTORY / "exp_lut.mif"
_VH_OUTPUT_PATH: Path = _LUT_DIRECTORY / "exp_lut.vh"
_PYTHON_OUTPUT_PATH: Path = _SCRIPT_DIRECTORY / "exp_lut_golden.py"


def build_exp_table(
    entry_count: int = _ENTRY_COUNT,
    log_price_min: float = _LOG_PRICE_MIN,
    log_price_max: float = _LOG_PRICE_MAX,
) -> tuple[NDArray[np.float64], NDArray[np.int64], float, int, int, int]:
    """Builds the quantized exp(L) lookup table and the hardware address scaling constants.

    Args:
        entry_count: The number of LUT entries to generate.
        log_price_min: The lower bound of the log-price range covered by the LUT.
        log_price_max: The upper bound of the log-price range covered by the LUT.

    Returns:
        A tuple containing the dense L-axis values, the Q8.24 quantized exp values, the L step size in float, the L
        step size in fixed-point, the reciprocal multiplier used for hardware address calculation, and the shift amount
        paired with that reciprocal.
    """
    log_price_step = (log_price_max - log_price_min) / entry_count
    log_price_values: NDArray[np.float64] = np.array(
        [log_price_min + index * log_price_step for index in range(entry_count)],
        dtype=np.float64,
    )
    exp_values = np.exp(log_price_values)
    exp_q824: NDArray[np.int64] = np.array(
        [min(int(round(value * (1 << _PRICE_FRAC))), _PRICE_MAX_INT) for value in exp_values],
        dtype=np.int64,
    )

    log_price_step_fixed = int(round(log_price_step * (1 << _LOG_PRICE_FRAC)))

    shift_amount = _RECIPROCAL_SHIFT_START
    while (1 << shift_amount) // log_price_step_fixed >= _RECIPROCAL_SHIFT_LIMIT:
        shift_amount -= 1
    log_price_step_reciprocal = int(round((1 << shift_amount) / log_price_step_fixed))

    return log_price_values, exp_q824, log_price_step, log_price_step_fixed, log_price_step_reciprocal, shift_amount


def write_mif(
    exp_q824: NDArray[np.int64],
    output_path: Path = _MIF_OUTPUT_PATH,
) -> None:
    """Writes the Quartus MIF image holding the Q8.24 exp(L) table.

    Args:
        exp_q824: The quantized exp(L) values indexed by LUT address.
        output_path: The destination path for the emitted MIF file.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "-- exp() LUT for gbm_logspace.v",
        "-- Generated by gen_exp_lut.py",
        f"-- L range: [{_LOG_PRICE_MIN}, {_LOG_PRICE_MAX}], N={len(exp_q824)}, Q8.24 output",
        "WIDTH = 32;",
        f"DEPTH = {len(exp_q824)};",
        "ADDRESS_RADIX = UNS;",
        "DATA_RADIX = UNS;",
        "CONTENT BEGIN",
    ]
    for index, value in enumerate(exp_q824):
        lines.append(f"    {index} : {int(value)};")
    lines.append("END;")

    output_path.write_text("\n".join(lines))
    print(f"Wrote {output_path}")


def write_verilog_header(
    exp_q824: NDArray[np.int64],
    log_price_step: float,
    output_path: Path = _VH_OUTPUT_PATH,
) -> None:
    """Writes a Verilog include file with a behavioral exp() lookup function for simulation.

    Args:
        exp_q824: The quantized exp(L) values indexed by LUT address.
        log_price_step: The L step size used to annotate the header file.
        output_path: The destination path for the emitted Verilog header.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "// exp_lut.vh - Behavioral exp() LUT for ModelSim",
        "// Generated by gen_exp_lut.py",
        f"// L range [{_LOG_PRICE_MIN:.3f}, {_LOG_PRICE_MAX:.3f}], step={log_price_step:.6f}",
        "",
        "function [31:0] exp_lut_lookup;",
        "    input [12:0] addr;",
        "    begin",
        "        case (addr)",
    ]
    for index, value in enumerate(exp_q824):
        lines.append(f"            13'd{index:<4d}: exp_lut_lookup = 32'h{int(value):08X};")
    lines.extend([
        "            default: exp_lut_lookup = 32'h00000000;",
        "        endcase",
        "    end",
        "endfunction",
    ])

    output_path.write_text("\n".join(lines))
    print(f"Wrote {output_path}")


def write_python_module(
    log_price_values: NDArray[np.float64],
    exp_q824: NDArray[np.int64],
    log_price_step: float,
    log_price_step_fixed: int,
    log_price_step_reciprocal: int,
    shift_amount: int,
    output_path: Path = _PYTHON_OUTPUT_PATH,
) -> None:
    """Writes the Python module consumed by the golden model.

    Emits the LUT contents alongside the address-scaling constants and a helper that mirrors the hardware lookup, so
    the golden model and the RTL produce bit-identical prices.

    Args:
        log_price_values: The dense L-axis values used to annotate each LUT entry.
        exp_q824: The quantized exp(L) values indexed by LUT address.
        log_price_step: The L step size emitted as the L_STEP constant.
        log_price_step_fixed: The L step size in Q0.24 fixed-point.
        log_price_step_reciprocal: The reciprocal multiplier paired with shift_amount.
        shift_amount: The right-shift amount that returns the LUT address from the multiply.
        output_path: The destination path for the emitted Python module.
    """
    log_price_min_fixed = int(round(_LOG_PRICE_MIN * (1 << _LOG_PRICE_FRAC)))

    lines: list[str] = [
        '"""Provides the quantized exp() lookup table and address-scaling helpers used by the GBM golden model."""',
        "",
        f"N_ENTRIES    = {len(exp_q824)}",
        f"L_MIN        = {_LOG_PRICE_MIN}",
        f"L_MAX        = {_LOG_PRICE_MAX}",
        f"L_STEP       = {log_price_step!r}",
        f"L_MIN_FIXED  = {log_price_min_fixed}",
        f"L_STEP_FIXED = {log_price_step_fixed}",
        f"L_STEP_RECIP = {log_price_step_reciprocal}",
        f"L_STEP_SHIFT = {shift_amount}",
        f"PRICE_FRAC   = {_PRICE_FRAC}",
        f"L_FRAC       = {_LOG_PRICE_FRAC}",
        "",
        "EXP_LUT = [",
    ]
    for index, value in enumerate(exp_q824):
        lines.append(f"    {int(value)},  # L={log_price_values[index]:.4f} -> exp={np.exp(log_price_values[index]):.4f}")
    lines.extend([
        "]",
        "",
        "",
        "def exp_lut_lookup(address: int) -> int:",
        '    """Returns the Q8.24 exp(L) value stored at the given LUT address, or zero if out of range.',
        "",
        "    Args:",
        "        address: The integer LUT address expected to fall in the half-open range [0, N_ENTRIES).",
        "",
        "    Returns:",
        "        The Q8.24 quantized exp(L) value, or zero when the address falls outside the table.",
        '    """',
        "    if 0 <= address < N_ENTRIES:",
        "        return EXP_LUT[address]",
        "    return 0",
        "",
        "",
        "def l_to_price(log_price_fixed: int) -> int:",
        '    """Converts a Q8.24 log-price integer into the matching Q8.24 price using the shared exp() LUT.',
        "",
        "    Mirrors the hardware address-from-L path bit-for-bit by subtracting the L_MIN offset, multiplying by the",
        "    precomputed reciprocal, and right-shifting to recover the LUT address. Inputs that fall outside the LUT",
        "    range saturate to the table endpoints, matching the RTL clamp behaviour.",
        "",
        "    Args:",
        "        log_price_fixed: The Q8.24 log-price integer to convert into a Q8.24 price.",
        "",
        "    Returns:",
        "        The Q8.24 quantized price retrieved from the exp() LUT.",
        '    """',
        "    offset = log_price_fixed - L_MIN_FIXED",
        "    if offset < 0:",
        "        return exp_lut_lookup(address=0)",
        "    address = (offset * L_STEP_RECIP) >> L_STEP_SHIFT",
        "    if address >= N_ENTRIES:",
        "        return exp_lut_lookup(address=N_ENTRIES - 1)",
        "    return exp_lut_lookup(address=int(address))",
    ])

    output_path.write_text("\n".join(lines))
    print(f"Wrote {output_path}")


def _print_lut_summary(
    log_price_step: float,
    log_price_step_fixed: int,
    log_price_step_reciprocal: int,
    shift_amount: int,
    exp_q824: NDArray[np.int64],
) -> None:
    """Prints the LUT configuration and hardware address scaling constants.

    Args:
        log_price_step: The L step size between adjacent LUT entries.
        log_price_step_fixed: The L step size in Q0.24 fixed-point.
        log_price_step_reciprocal: The reciprocal multiplier paired with shift_amount.
        shift_amount: The right-shift amount that returns the LUT address from the multiply.
        exp_q824: The quantized exp(L) values used for spot checks.
    """
    log_price_min_fixed = int(round(_LOG_PRICE_MIN * (1 << _LOG_PRICE_FRAC)))

    print("LUT configuration:")
    print(f"  N_ENTRIES    = {len(exp_q824)}")
    print(f"  L range      = [{_LOG_PRICE_MIN:.3f}, {_LOG_PRICE_MAX:.3f}]")
    print(f"  L_step       = {log_price_step:.6f}")
    print(f"  L_MIN_FIXED  = {log_price_min_fixed} (32'h{log_price_min_fixed & 0xFFFFFFFF:08X})")
    print(f"  L_STEP_FIXED = {log_price_step_fixed} (32'h{log_price_step_fixed:08X})")
    print(f"  L_STEP_RECIP = {log_price_step_reciprocal} (32'h{log_price_step_reciprocal:08X})")
    print(f"  VERILOG SHIFT AMOUNT = {shift_amount}")
    print(f"  VERILOG EXTRACTION   = addr_full_wire[{shift_amount + _VERILOG_ADDRESS_LOWER_OFFSET}:{shift_amount}]")
    print(f"  exp_q824 spot checks: [0]={exp_q824[0]}, [4095]={exp_q824[4095]}, [8191]={exp_q824[8191]}")


def _print_quantization_error(
    log_price_values: NDArray[np.float64],
    exp_q824: NDArray[np.int64],
) -> None:
    """Prints the maximum absolute and relative quantization error across the LUT.

    Args:
        log_price_values: The dense L-axis values used to evaluate the reference exp(L).
        exp_q824: The quantized exp(L) values indexed by LUT address.
    """
    exp_values = np.exp(log_price_values)
    max_absolute_error = 0.0
    max_relative_error = 0.0
    for index in range(len(exp_q824)):
        real_value = exp_q824[index] / (1 << _PRICE_FRAC)
        clamped_value = min(exp_values[index], _PRICE_MAX_INT / (1 << _PRICE_FRAC))
        absolute_error = abs(real_value - clamped_value)
        relative_error = absolute_error / clamped_value
        max_absolute_error = max(max_absolute_error, absolute_error)
        max_relative_error = max(max_relative_error, relative_error)

    print("\nQuantization error:")
    print(f"  Max absolute error: {max_absolute_error:.6e}")
    print(f"  Max relative error: {max_relative_error * 100:.4f}%")


def main() -> None:
    """Runs the full table-generation pipeline and emits all three artifacts."""
    log_price_values, exp_q824, log_price_step, log_price_step_fixed, log_price_step_reciprocal, shift_amount = (
        build_exp_table()
    )

    _print_lut_summary(
        log_price_step=log_price_step,
        log_price_step_fixed=log_price_step_fixed,
        log_price_step_reciprocal=log_price_step_reciprocal,
        shift_amount=shift_amount,
        exp_q824=exp_q824,
    )
    _print_quantization_error(log_price_values=log_price_values, exp_q824=exp_q824)

    write_mif(exp_q824=exp_q824)
    write_verilog_header(exp_q824=exp_q824, log_price_step=log_price_step)
    write_python_module(
        log_price_values=log_price_values,
        exp_q824=exp_q824,
        log_price_step=log_price_step,
        log_price_step_fixed=log_price_step_fixed,
        log_price_step_reciprocal=log_price_step_reciprocal,
        shift_amount=shift_amount,
    )


if __name__ == "__main__":
    main()
