"""Precomputes the 256-layer Ziggurat tables for the standard normal distribution.

Uses the Marsaglia and Tsang (2000) construction and emits the Q4.12 tables in the three
formats consumed downstream: a Quartus M10K .mif ROM image, a Verilog header with behavioral
ROM functions for simulation, and a Python module imported by the golden model.
"""

import math
from pathlib import Path

import numpy as np
from numpy.typing import NDArray
from scipy.optimize import brentq

_LAYER_COUNT: int = 256
_Q_SCALE: int = 4096               # Q4.12 scale factor (2^12)
_Q_SIGNED_MIN: int = -32768
_Q_SIGNED_MAX: int = 32767
_Q_UNSIGNED_MASK: int = 0xFFFF
_TAIL_SEARCH_LOWER: float = 2.0
_TAIL_SEARCH_UPPER: float = 4.0

_SCRIPT_DIR: Path = Path(__file__).resolve().parent
_RTL_DIR: Path = _SCRIPT_DIR.parent / "rtl"
_MIF_OUTPUT_PATH: Path = _RTL_DIR / "ziggurat_tables.mif"
_VH_OUTPUT_PATH: Path = _RTL_DIR / "ziggurat_tables.vh"
_PYTHON_OUTPUT_PATH: Path = _SCRIPT_DIR / "ziggurat_tables_golden.py"


def build_ziggurat_tables(
    layer_count: int = _LAYER_COUNT,
) -> tuple[list[float], list[float], float, float]:
    """Builds the Ziggurat layer coordinates for the standard normal distribution.

    Solves for the tail-start coordinate `r` such that every layer has equal area, then walks
    upward from the bottom layer to the peak to produce the layer x- and y-coordinates.

    Notes:
        The construction follows Marsaglia and Tsang (2000). The bottom layer (index
        layer_count - 1) includes the bounding-box width and tail area; the peak layer (index 0)
        is pinned at (0, 1).

    Args:
        layer_count: The number of Ziggurat layers. Defaults to the module-level constant.

    Returns:
        A tuple containing the x-coordinate table, the y-coordinate table, the tail-start
        coordinate `r`, and the per-layer volume `v`.
    """
    target_area = math.sqrt(math.pi / 2.0)

    def equations(tail_start: float) -> float:
        tail = math.sqrt(math.pi / 2.0) * math.erfc(tail_start / math.sqrt(2.0))
        return (tail_start * _norm_pdf_unnorm(value=tail_start) + tail) - target_area / layer_count

    tail_start = brentq(equations, _TAIL_SEARCH_LOWER, _TAIL_SEARCH_UPPER)
    layer_volume = (
        tail_start * _norm_pdf_unnorm(value=tail_start)
        + math.sqrt(math.pi / 2.0) * math.erfc(tail_start / math.sqrt(2.0))
    )

    x_table: list[float] = [0.0] * layer_count
    y_table: list[float] = [0.0] * layer_count

    # Layer layer_count - 1 is the bottom layer and includes the bounding-box width.
    x_table[layer_count - 1] = layer_volume / _norm_pdf_unnorm(value=tail_start)
    x_table[layer_count - 2] = tail_start
    y_table[layer_count - 1] = _norm_pdf_unnorm(value=tail_start)
    y_table[layer_count - 2] = _norm_pdf_unnorm(value=tail_start)

    # Walks upward from the bottom layer toward the peak.
    for index in range(layer_count - 3, -1, -1):
        x_table[index] = math.sqrt(-2.0 * math.log(layer_volume / x_table[index + 1] + y_table[index + 1]))
        y_table[index] = _norm_pdf_unnorm(value=x_table[index])

    # Pins the peak layer exactly at (0, 1).
    x_table[0] = 0.0
    y_table[0] = 1.0

    return x_table, y_table, tail_start, layer_volume


def to_q412(value: float, saturate: bool = True) -> int:
    """Converts a floating-point value to its Q4.12 signed 16-bit representation.

    Args:
        value: The floating-point value to quantize.
        saturate: Determines whether out-of-range values are clamped to the signed 16-bit
            range. When False, values wrap around modulo 16 bits.

    Returns:
        The Q4.12 representation as an unsigned 16-bit integer suitable for hex emission.
    """
    scaled = round(value * _Q_SCALE)
    if saturate:
        scaled = max(_Q_SIGNED_MIN, min(_Q_SIGNED_MAX, scaled))
    return scaled & _Q_UNSIGNED_MASK


def write_mif(
    x_table: list[float],
    y_table: list[float],
    output_path: Path = _MIF_OUTPUT_PATH,
) -> None:
    """Writes the Quartus MIF image for the 512x16 ROM.

    The lower 256 words hold the x-table; the upper 256 words hold the y-table.

    Args:
        x_table: The x-coordinate table indexed by layer.
        y_table: The y-coordinate table indexed by layer.
        output_path: The destination path for the emitted .mif file.
    """
    layer_count = len(x_table)
    assert len(y_table) == layer_count == _LAYER_COUNT

    lines: list[str] = [
        "-- Ziggurat N(0,1) lookup tables",
        "-- Generated by gen_ziggurat_tables.py",
        "-- Format: Q4.12 signed fixed-point (stored as unsigned hex)",
        "-- Addresses 0x000..0x0FF: x_table[0..255]",
        "-- Addresses 0x100..0x1FF: y_table[0..255]",
        "WIDTH=16;",
        "DEPTH=512;",
        "ADDRESS_RADIX=HEX;",
        "DATA_RADIX=HEX;",
        "CONTENT BEGIN",
    ]

    for index in range(layer_count):
        quantized = to_q412(value=x_table[index])
        lines.append(f"\t{index:03X} : {quantized:04X};  -- x[{index}] = {x_table[index]:.6f}")

    for index in range(layer_count):
        quantized = to_q412(value=y_table[index])
        lines.append(f"\t{index + layer_count:03X} : {quantized:04X};  -- y[{index}] = {y_table[index]:.6f}")

    lines.append("END;")

    output_path.write_text("\n".join(lines))
    print(f"Wrote {output_path}  ({2 * layer_count} entries, 512x16 ROM)")


def write_verilog_header(
    x_table: list[float],
    y_table: list[float],
    output_path: Path = _VH_OUTPUT_PATH,
) -> None:
    """Writes a Verilog include file with behavioral ROM functions for simulation.

    The generated functions return each table entry by index through a case statement, which
    ModelSim can elaborate without synthesis-specific M10K primitives.

    Args:
        x_table: The x-coordinate table indexed by layer.
        y_table: The y-coordinate table indexed by layer.
        output_path: The destination path for the emitted Verilog header.
    """
    layer_count = len(x_table)
    lines: list[str] = [
        "// ziggurat_tables.vh",
        "// Auto-generated by gen_ziggurat_tables.py",
        "// Q4.12 fixed-point Ziggurat tables for N(0,1), 256 layers",
        "// Include in ziggurat_gaussian.v for behavioral simulation",
        "// For synthesis: use ziggurat_tables.mif with M10K ROM",
        "",
        "// x_table: layer right-edge x-coordinates",
        "// y_table: layer y-coordinates (= f(x[i]) = exp(-0.5*x[i]^2))",
        "",
        "// Behavioral ROM function - replace with M10K in synthesis",
        "function [15:0] zig_x_rom;",
        "    input [7:0] idx;",
        "    case (idx)",
    ]
    for index in range(layer_count):
        quantized = to_q412(value=x_table[index])
        lines.append(f"        8'd{index}: zig_x_rom = 16'h{quantized:04X}; // {x_table[index]:.6f}")
    lines.extend([
        "        default: zig_x_rom = 16'h0000;",
        "    endcase",
        "endfunction",
        "",
        "function [15:0] zig_y_rom;",
        "    input [7:0] idx;",
        "    case (idx)",
    ])
    for index in range(layer_count):
        quantized = to_q412(value=y_table[index])
        lines.append(f"        8'd{index}: zig_y_rom = 16'h{quantized:04X}; // {y_table[index]:.6f}")
    lines.extend([
        "        default: zig_y_rom = 16'h0000;",
        "    endcase",
        "endfunction",
    ])

    output_path.write_text("\n".join(lines))
    print(f"Wrote {output_path}  (Verilog behavioral ROM functions)")


def write_python_module(
    x_table: list[float],
    y_table: list[float],
    tail_start: float,
    layer_volume: float,
    output_path: Path = _PYTHON_OUTPUT_PATH,
) -> None:
    """Writes the Python module consumed by the golden model.

    Emits both the raw Q4.12 integer tables and the dequantized float tables so the golden
    model can exercise either representation.

    Args:
        x_table: The x-coordinate table indexed by layer.
        y_table: The y-coordinate table indexed by layer.
        tail_start: The tail-start coordinate `r` returned by the Ziggurat construction.
        layer_volume: The per-layer volume `v` returned by the Ziggurat construction.
        output_path: The destination path for the emitted Python module.
    """
    layer_count = len(x_table)
    x_quantized = [to_q412(value=entry) for entry in x_table]
    y_quantized = [to_q412(value=entry) for entry in y_table]

    lines: list[str] = [
        '"""Auto-generated Ziggurat tables for the N(0,1) golden model.',
        "",
        "Q4.12 quantized tables match the hardware ROM exactly. Float tables are dequantized",
        "for convenience in the Python golden model.",
        '"""',
        f"N_LAYERS = {layer_count}",
        f"TAIL_START_R = {tail_start:.10f}  # x[N-1], tail begins here",
        f"LAYER_VOLUME_V = {layer_volume:.10f}  # per-layer area",
        f"Q_SCALE = {_Q_SCALE}  # Q4.12",
        "",
        f"X_TABLE_RAW = {x_quantized}",
        f"Y_TABLE_RAW = {y_quantized}",
        "",
        "X_TABLE = [entry / Q_SCALE for entry in X_TABLE_RAW]",
        "Y_TABLE = [entry / Q_SCALE for entry in Y_TABLE_RAW]",
    ]

    output_path.write_text("\n".join(lines))
    print(f"Wrote {output_path}  (Python golden-model tables)")


def _norm_pdf_unnorm(value: float) -> float:
    """Evaluates the unnormalized standard-normal PDF at the requested point.

    Args:
        value: The point at which to evaluate the unnormalized PDF f(x) = exp(-0.5 * x**2).

    Returns:
        The unnormalized PDF value.
    """
    return math.exp(-0.5 * value * value)


def _print_layer_area_uniformity(x_table: list[float], y_table: list[float]) -> None:
    """Prints the min, max, and standard deviation of the per-layer areas.

    Args:
        x_table: The x-coordinate table indexed by layer.
        y_table: The y-coordinate table indexed by layer.
    """
    areas: list[float] = []
    for index in range(1, len(x_table)):
        areas.append((x_table[index] - x_table[index - 1]) * y_table[index])
    area_array: NDArray[np.float64] = np.array(areas, dtype=np.float64)
    print(
        f"  Layer area uniformity: min={min(areas):.6f}, max={max(areas):.6f}, "
        f"std={float(np.std(area_array)):.2e}"
    )


def main() -> None:
    """Runs the full table-generation pipeline and emits all three artifacts."""
    print(f"Building Ziggurat N(0,1) tables (N={_LAYER_COUNT}, Q4.12)...")
    x_table, y_table, tail_start, layer_volume = build_ziggurat_tables(layer_count=_LAYER_COUNT)

    print(f"  Tail start r = {tail_start:.6f}")
    print(f"  Layer volume v = {layer_volume:.8f}")
    print(f"  x[0]   = {x_table[0]:.6f}  (should be 0.0)")
    print(f"  x[{_LAYER_COUNT - 1}] = {x_table[_LAYER_COUNT - 1]:.6f}  (should be ~{tail_start:.4f})")
    print(f"  y[0]   = {y_table[0]:.6f}  (should be 1.0)")
    print(
        f"  y[{_LAYER_COUNT - 1}] = {y_table[_LAYER_COUNT - 1]:.6f}  "
        f"(should be ~{math.exp(-0.5 * tail_start * tail_start):.4f})"
    )

    _print_layer_area_uniformity(x_table=x_table, y_table=y_table)

    write_mif(x_table=x_table, y_table=y_table)
    write_verilog_header(x_table=x_table, y_table=y_table)
    write_python_module(
        x_table=x_table,
        y_table=y_table,
        tail_start=tail_start,
        layer_volume=layer_volume,
    )

    print("\nDone. Files generated:")
    print(f"  Quartus M10K ROM image:              {_MIF_OUTPUT_PATH}")
    print(f"  Verilog behavioral ROM header:       {_VH_OUTPUT_PATH}")
    print(f"  Python golden-model tables module:   {_PYTHON_OUTPUT_PATH}")


if __name__ == "__main__":
    main()