"""Precomputes Ziggurat lookup tables for the standard normal distribution.

Builds the 256-layer Marsaglia and Tsang ziggurat decomposition for N(0, 1) and emits the Q4.12 tables as a Quartus
MIF, a Verilog include, and a Python module so the float, MIF, Verilog, and golden-model representations agree
bit-for-bit.
"""

import math
from pathlib import Path

import numpy as np
from scipy.optimize import brentq

_LAYER_COUNT: int = 256
_Q_SCALE: int = 4096
_Q_INT16_MIN: int = -32768
_Q_INT16_MAX: int = 32767
_GOLDEN_TABLE_ROW_WIDTH: int = 16
_SCRIPT_DIRECTORY: Path = Path(__file__).resolve().parent
_LUT_DIRECTORY: Path = _SCRIPT_DIRECTORY.parent / "rtl" / "lut"
_MIF_PATH: Path = _LUT_DIRECTORY / "ziggurat_tables.mif"
_VERILOG_HEADER_PATH: Path = _LUT_DIRECTORY / "ziggurat_tables.vh"
_GOLDEN_MODULE_PATH: Path = _SCRIPT_DIRECTORY / "ziggurat_tables_golden.py"


def build_ziggurat_tables(
    layer_count: int = _LAYER_COUNT,
) -> tuple[list[float], list[float], float, float]:
    """Constructs the Marsaglia and Tsang ziggurat decomposition for N(0, 1).

    Solves for the tail-start radius and per-layer area such that all rectangles in the
    decomposition cover equal area, then walks from the bottom layer to the peak to fill in the
    right-edge x-coordinates and matching y-values for every layer.

    Args:
        layer_count: The number of equal-area ziggurat layers to construct.

    Returns:
        A tuple of (x_table, y_table, tail_start_radius, layer_area). x_table contains the
        right-edge x-coordinate of each layer, y_table contains the unnormalized density at each
        right edge, tail_start_radius is the x-coordinate where the exponential tail begins, and
        layer_area is the common area shared by every ziggurat layer.
    """
    target_area = math.sqrt(math.pi / 2.0)

    def compute_area_residual(radius: float) -> float:
        tail = math.sqrt(math.pi / 2.0) * math.erfc(radius / math.sqrt(2.0))
        return (radius * _normal_pdf_unnormalized(value=radius) + tail) - target_area / layer_count

    tail_start_radius = brentq(f=compute_area_residual, a=2.0, b=4.0)
    layer_area = (
        tail_start_radius * _normal_pdf_unnormalized(value=tail_start_radius)
        + math.sqrt(math.pi / 2.0) * math.erfc(tail_start_radius / math.sqrt(2.0))
    )

    x_table: list[float] = [0.0] * layer_count
    y_table: list[float] = [0.0] * layer_count

    # Sets the bottom layer right edge to layer_area / f(tail_start_radius) and pins the layer
    # above to the tail-start radius, since the recursive build cannot derive these two anchors.
    x_table[layer_count - 1] = layer_area / _normal_pdf_unnormalized(value=tail_start_radius)
    x_table[layer_count - 2] = tail_start_radius
    y_table[layer_count - 1] = _normal_pdf_unnormalized(value=tail_start_radius)
    y_table[layer_count - 2] = _normal_pdf_unnormalized(value=tail_start_radius)

    for layer_index in range(layer_count - 3, -1, -1):
        x_table[layer_index] = math.sqrt(
            -2.0 * math.log(layer_area / x_table[layer_index + 1] + y_table[layer_index + 1])
        )
        y_table[layer_index] = _normal_pdf_unnormalized(value=x_table[layer_index])

    # Overrides the recursive estimate for the top layer with the exact N(0, 1) mode at (0, 1).
    x_table[0] = 0.0
    y_table[0] = 1.0

    return x_table, y_table, tail_start_radius, layer_area


def write_mif(x_table: list[float], y_table: list[float], output_path: Path) -> None:
    """Writes a Quartus MIF file for the 512x16 ziggurat ROM.

    The lower 256 words store x_table and the upper 256 words store y_table, each in Q4.12
    signed fixed-point packed as unsigned 16-bit hex.

    Args:
        x_table: The per-layer right-edge x-coordinates in float units.
        y_table: The per-layer y-values in float units.
        output_path: The destination MIF path.

    Raises:
        ValueError: When either table does not contain exactly _LAYER_COUNT entries.
    """
    if len(x_table) != _LAYER_COUNT or len(y_table) != _LAYER_COUNT:
        message = (
            f"Unable to write the MIF file. Both ziggurat tables must contain exactly "
            f"{_LAYER_COUNT} entries, but got {len(x_table)} and {len(y_table)}."
        )
        raise ValueError(message)

    lines: list[str] = [
        "-- Ziggurat N(0,1) lookup tables",
        "-- Generated by gen_ziggurat_tables.py",
        "-- Format: Q4.12 signed fixed-point (stored as unsigned hex)",
        "-- Addresses 0x000..0x0FF: x_table[0..255]",
        "-- Addresses 0x100..0x1FF: y_table[0..255]",
        "WIDTH=16;",
        "DEPTH=512;",
        "ADDRESS_RADIX=HEX;",
        "DATA_RADIX=HEX;",
        "CONTENT BEGIN",
    ]

    for index in range(_LAYER_COUNT):
        x_quantized = _quantize_to_q412(value=x_table[index])
        lines.append(f"\t{index:03X} : {x_quantized:04X};  -- x[{index}] = {x_table[index]:.6f}")

    for index in range(_LAYER_COUNT):
        y_quantized = _quantize_to_q412(value=y_table[index])
        lines.append(
            f"\t{index + _LAYER_COUNT:03X} : {y_quantized:04X};  -- y[{index}] = {y_table[index]:.6f}"
        )

    lines.append("END;")

    output_path.write_text("\n".join(lines))
    print(f"Wrote {output_path}  ({2 * _LAYER_COUNT} entries, 512x16 ROM)")


def write_verilog_header(x_table: list[float], y_table: list[float], output_path: Path) -> None:
    """Writes a behavioral Verilog include that exposes the ROM as case-statement functions.

    The emitted header is intended for ModelSim behavioral simulation. Synthesis builds use the
    MIF-initialized M10K ROM rather than this header.

    Args:
        x_table: The per-layer right-edge x-coordinates in float units.
        y_table: The per-layer y-values in float units.
        output_path: The destination Verilog include path.
    """
    lines: list[str] = [
        "// ziggurat_tables.vh",
        "// Auto-generated by gen_ziggurat_tables.py",
        "// Q4.12 fixed-point Ziggurat tables for N(0,1), 256 layers",
        "// Include in ziggurat_gaussian.v for behavioral simulation",
        "// For synthesis: use ziggurat_tables.mif with M10K ROM",
        "",
        "// x_table: layer right-edge x-coordinates",
        "// y_table: layer y-coordinates (= f(x[i]) = exp(-0.5*x[i]^2))",
        "",
        "// Behavioral ROM function - replace with M10K in synthesis",
        "function [15:0] zig_x_rom;",
        "    input [7:0] idx;",
        "    case (idx)",
    ]
    for index in range(_LAYER_COUNT):
        x_quantized = _quantize_to_q412(value=x_table[index])
        lines.append(
            f"        8'd{index}: zig_x_rom = 16'h{x_quantized:04X}; // {x_table[index]:.6f}"
        )
    lines.extend(
        [
            "        default: zig_x_rom = 16'h0000;",
            "    endcase",
            "endfunction",
            "",
            "function [15:0] zig_y_rom;",
            "    input [7:0] idx;",
            "    case (idx)",
        ]
    )
    for index in range(_LAYER_COUNT):
        y_quantized = _quantize_to_q412(value=y_table[index])
        lines.append(
            f"        8'd{index}: zig_y_rom = 16'h{y_quantized:04X}; // {y_table[index]:.6f}"
        )
    lines.extend(
        [
            "        default: zig_y_rom = 16'h0000;",
            "    endcase",
            "endfunction",
        ]
    )

    output_path.write_text("\n".join(lines))
    print(f"Wrote {output_path}  (Verilog behavioral ROM functions)")


def write_python_module(
    x_table: list[float],
    y_table: list[float],
    tail_start_radius: float,
    layer_area: float,
    output_path: Path,
) -> None:
    """Writes a Python module that mirrors the hardware ROM for the gaussian_verify golden model.

    The emitted module exposes the Q4.12 quantized tables and recovers the float representation
    by dividing by the shared scale factor. The float values match the M10K ROM contents
    bit-for-bit, so the golden model and the FPGA path operate on identical data.

    Args:
        x_table: The per-layer right-edge x-coordinates in float units.
        y_table: The per-layer y-values in float units.
        tail_start_radius: The x-coordinate where the exponential tail begins.
        layer_area: The common per-layer area in the ziggurat decomposition.
        output_path: The destination Python module path.
    """
    x_quantized = [_quantize_to_q412(value=value) for value in x_table]
    y_quantized = [_quantize_to_q412(value=value) for value in y_table]

    lines: list[str] = [
        '"""Q4.12 Ziggurat lookup tables for the N(0, 1) golden model.',
        "",
        "Mirrors the hardware ROM bit-for-bit. Auto-generated by gen_ziggurat_tables.py.",
        '"""',
        "",
        f"LAYER_COUNT: int = {len(x_table)}",
        f"TAIL_START_RADIUS: float = {tail_start_radius:.10f}",
        f"LAYER_AREA: float = {layer_area:.10f}",
        f"Q_SCALE: int = {_Q_SCALE}",
        "",
        "X_TABLE_RAW: tuple[int, ...] = (",
        _format_int_tuple_body(values=x_quantized),
        ")",
        "Y_TABLE_RAW: tuple[int, ...] = (",
        _format_int_tuple_body(values=y_quantized),
        ")",
        "",
        "X_TABLE: tuple[float, ...] = tuple(value / Q_SCALE for value in X_TABLE_RAW)",
        "Y_TABLE: tuple[float, ...] = tuple(value / Q_SCALE for value in Y_TABLE_RAW)",
        "",
    ]

    output_path.write_text("\n".join(lines))
    print(f"Wrote {output_path}  (Python golden model tables)")


def main() -> None:
    """Generates the three Ziggurat lookup table artifacts and prints construction diagnostics."""
    print("Building Ziggurat N(0,1) tables (N=256, Q4.12)...")
    x_table, y_table, tail_start_radius, layer_area = build_ziggurat_tables(
        layer_count=_LAYER_COUNT,
    )

    print(f"  Tail start r = {tail_start_radius:.6f}")
    print(f"  Layer volume v = {layer_area:.8f}")
    print(f"  x[0]   = {x_table[0]:.6f}  (should be 0.0)")
    print(
        f"  x[{_LAYER_COUNT - 1}] = {x_table[_LAYER_COUNT - 1]:.6f}  "
        f"(should be ~{tail_start_radius:.4f})"
    )
    print(f"  y[0]   = {y_table[0]:.6f}  (should be 1.0)")
    print(
        f"  y[{_LAYER_COUNT - 1}] = {y_table[_LAYER_COUNT - 1]:.6f}  "
        f"(should be ~{math.exp(-0.5 * tail_start_radius * tail_start_radius):.4f})"
    )

    layer_areas = [
        (x_table[index] - x_table[index - 1]) * y_table[index]
        for index in range(1, _LAYER_COUNT)
    ]
    print(
        f"  Layer area uniformity: min={min(layer_areas):.6f}, max={max(layer_areas):.6f}, "
        f"std={np.std(layer_areas):.2e}"
    )

    write_mif(x_table=x_table, y_table=y_table, output_path=_MIF_PATH)
    write_verilog_header(x_table=x_table, y_table=y_table, output_path=_VERILOG_HEADER_PATH)
    write_python_module(
        x_table=x_table,
        y_table=y_table,
        tail_start_radius=tail_start_radius,
        layer_area=layer_area,
        output_path=_GOLDEN_MODULE_PATH,
    )

    print("\nDone. Files generated:")
    print(f"  {_MIF_PATH}           -> load into Quartus M10K ROM")
    print(f"  {_VERILOG_HEADER_PATH}            -> include in Verilog for ModelSim")
    print(f"  {_GOLDEN_MODULE_PATH}     -> import in cross_check.py")


def _normal_pdf_unnormalized(value: float) -> float:
    """Evaluates the unnormalized standard-normal density used in the ziggurat construction.

    Args:
        value: The point at which the density is evaluated.

    Returns:
        The value of exp(-0.5 * value * value), the unnormalized N(0, 1) density.
    """
    return math.exp(-0.5 * value * value)


def _quantize_to_q412(value: float, saturate: bool = True) -> int:
    """Converts a floating-point value to a Q4.12 signed 16-bit integer.

    Args:
        value: The value to quantize.
        saturate: Determines whether out-of-range results are clamped to the signed 16-bit range
            before the unsigned modulo cast.

    Returns:
        The unsigned 16-bit representation of the Q4.12 quantized value.
    """
    scaled = round(value * _Q_SCALE)
    if saturate:
        scaled = max(_Q_INT16_MIN, min(_Q_INT16_MAX, scaled))
    return scaled & 0xFFFF


def _format_int_tuple_body(
    values: list[int],
    items_per_row: int = _GOLDEN_TABLE_ROW_WIDTH,
    indent: str = "    ",
) -> str:
    """Formats a list of integers as the wrapped body of a tuple literal.

    Args:
        values: The integer sequence to format.
        items_per_row: The number of integers placed on a single output line.
        indent: The leading whitespace prepended to each output row.

    Returns:
        A newline-separated string of indented rows, each ending with a trailing comma so that
        the closing parenthesis can be placed on its own line by the caller.
    """
    rows: list[str] = []
    for start_index in range(0, len(values), items_per_row):
        chunk = values[start_index:start_index + items_per_row]
        rows.append(indent + ", ".join(str(value) for value in chunk) + ",")
    return "\n".join(rows)


if __name__ == "__main__":
    main()
