"""Provides a Python golden model for the matching_engine Verilog module."""

from __future__ import annotations

import csv
import random
import sys
from dataclasses import dataclass, field
from pathlib import Path

import click

from ...utilities import console
from .price_level_store_no_cancellation_golden import PriceLevelStoreNoCancellation


# Number of addressable price ticks (must match kPriceRange in the Verilog DUT).
_DEFAULT_PRICE_RANGE: int = 480

# Default seed for deterministic stimulus generation.
_DEFAULT_SEED: int = 42

# Packet-field decode bit positions (must match matching_engine.v and agent_execution_unit.v).
_PACKET_SIDE_BIT: int = 31
_PACKET_TYPE_BIT: int = 30
_PACKET_AGENT_SHIFT: int = 28
_PACKET_AGENT_MASK: int = 0x3
_PACKET_PRICE_SHIFT: int = 16
_PACKET_PRICE_MASK: int = 0x1FF
_PACKET_VOLUME_MASK: int = 0xFFFF


@dataclass
class TradeRecord:
    """Captures a single trade execution.

    Attributes:
        price: The execution price (opposite side's best price at the time of the fill).
        quantity: The number of shares filled in this trade.
        side: 0 when the incoming (aggressor) order was a buy, 1 when it was a sell.
    """

    price: int
    """The execution price."""
    quantity: int
    """The number of shares filled in this trade."""
    side: int
    """0 = buy aggressor, 1 = sell aggressor."""


@dataclass
class StepRecord:
    """Captures the complete state after processing one order packet.

    Attributes:
        step: The packet index in the input sequence.
        packet: The raw 32-bit order packet.
        side: Decoded side field (0 = buy, 1 = sell).
        order_type: Decoded order type (0 = limit, 1 = market).
        agent_type: Decoded agent type (00 = noise, 01 = mm, 10 = momentum, 11 = value).
        price: Decoded 9-bit tick price from the packet.
        volume: Decoded 16-bit share count from the packet.
        trades: The list of trades generated by this packet.
        best_bid_price: The best bid price after processing.
        best_bid_quantity: The aggregate quantity at the best bid.
        best_bid_valid: Determines whether the bid book is nonempty.
        best_ask_price: The best ask price after processing.
        best_ask_quantity: The aggregate quantity at the best ask.
        best_ask_valid: Determines whether the ask book is nonempty.
        last_trade_price: The most recently executed trade price after processing this packet.
        last_trade_price_valid: Determines whether at least one trade has executed yet.
        total_trades: The cumulative trade count.
        total_volume: The cumulative shares traded.
    """

    step: int
    """The packet index in the input sequence."""
    packet: int
    """The raw 32-bit order packet."""
    side: int
    """Decoded side field (0 = buy, 1 = sell)."""
    order_type: int
    """Decoded order type (0 = limit, 1 = market)."""
    agent_type: int
    """Decoded agent type (00 = noise, 01 = mm, 10 = momentum, 11 = value)."""
    price: int
    """Decoded 9-bit tick price from the packet."""
    volume: int
    """Decoded 16-bit share count from the packet."""
    trades: list[TradeRecord] = field(default_factory=list)
    """The list of trades generated by this packet."""
    best_bid_price: int = 0
    """The best bid price after processing."""
    best_bid_quantity: int = 0
    """The aggregate quantity at the best bid."""
    best_bid_valid: bool = False
    """Determines whether the bid book is nonempty."""
    best_ask_price: int = 0
    """The best ask price after processing."""
    best_ask_quantity: int = 0
    """The aggregate quantity at the best ask."""
    best_ask_valid: bool = False
    """Determines whether the ask book is nonempty."""
    last_trade_price: int = 0
    """The most recently executed trade price after processing this packet."""
    last_trade_price_valid: bool = False
    """Determines whether at least one trade has executed yet."""
    total_trades: int = 0
    """The cumulative trade count."""
    total_volume: int = 0
    """The cumulative shares traded."""


def encode_packet(side: int, order_type: int, agent_type: int, price: int, volume: int) -> int:
    """Packs order fields into the 32-bit packet layout consumed by the engine.

    Args:
        side: 0 = buy, 1 = sell.
        order_type: 0 = limit, 1 = market.
        agent_type: 0..3 identifying the emitting agent class.
        price: 9-bit tick price (0..kPriceRange-1).
        volume: 16-bit share count.

    Returns:
        The packed 32-bit packet value.
    """
    packet = (side & 0x1) << _PACKET_SIDE_BIT
    packet |= (order_type & 0x1) << _PACKET_TYPE_BIT
    packet |= (agent_type & _PACKET_AGENT_MASK) << _PACKET_AGENT_SHIFT
    packet |= (price & _PACKET_PRICE_MASK) << _PACKET_PRICE_SHIFT
    packet |= volume & _PACKET_VOLUME_MASK
    return packet


def decode_packet(packet: int) -> tuple[int, int, int, int, int]:
    """Unpacks a 32-bit order packet into its field values.

    Args:
        packet: The raw 32-bit packet value.

    Returns:
        A tuple of (side, order_type, agent_type, price, volume).
    """
    side = (packet >> _PACKET_SIDE_BIT) & 0x1
    order_type = (packet >> _PACKET_TYPE_BIT) & 0x1
    agent_type = (packet >> _PACKET_AGENT_SHIFT) & _PACKET_AGENT_MASK
    price = (packet >> _PACKET_PRICE_SHIFT) & _PACKET_PRICE_MASK
    volume = packet & _PACKET_VOLUME_MASK
    return side, order_type, agent_type, price, volume


class MatchingEngine:
    """Replicates the matching_engine Verilog module's order processing logic.

    Maintains a bid book and an ask book using the aggregate-quantity no-cancellation store.
    Processes incoming order packets by matching against the opposite side; any unmatched limit
    remainder is inserted into the same-side book. Market orders never insert. Tracks trade
    executions and cumulative statistics identically to the hardware.

    Args:
        price_range: The number of addressable price ticks, matching kPriceRange in the DUT.

    Attributes:
        price_range: Cached price-tick range parameter.
        _bid_book: The bid-side price level store.
        _ask_book: The ask-side price level store.
        _last_trade_price: The most recently executed trade price.
        _last_trade_price_valid: Determines whether at least one trade has executed.
        _total_trades: The cumulative trade count.
        _total_volume: The cumulative shares traded.
    """

    def __init__(self, price_range: int = _DEFAULT_PRICE_RANGE) -> None:
        self.price_range: int = price_range
        self._bid_book: PriceLevelStoreNoCancellation = PriceLevelStoreNoCancellation(
            is_bid=True, price_range=price_range,
        )
        self._ask_book: PriceLevelStoreNoCancellation = PriceLevelStoreNoCancellation(
            is_bid=False, price_range=price_range,
        )
        self._last_trade_price: int = 0
        self._last_trade_price_valid: bool = False
        self._total_trades: int = 0
        self._total_volume: int = 0

    def __repr__(self) -> str:
        """Returns a string representation of the MatchingEngine instance."""
        return (
            f"MatchingEngine(total_trades={self._total_trades}, "
            f"total_volume={self._total_volume})"
        )

    @property
    def total_trades(self) -> int:
        """Returns the cumulative trade count."""
        return self._total_trades

    @property
    def total_volume(self) -> int:
        """Returns the cumulative shares traded."""
        return self._total_volume

    @property
    def last_trade_price(self) -> int:
        """Returns the most recently executed trade price (0 before any trade has occurred)."""
        return self._last_trade_price

    @property
    def last_trade_price_valid(self) -> bool:
        """Returns True after the first trade has executed."""
        return self._last_trade_price_valid

    def process_packet(self, packet: int) -> list[TradeRecord]:
        """Processes a single order packet and returns the resulting trades.

        Args:
            packet: The raw 32-bit order packet.

        Returns:
            A list of TradeRecord instances, one per level consumed.
        """
        side, order_type, _, price, volume = decode_packet(packet=packet)
        is_buy = side == 0
        is_market = order_type == 1
        remaining = volume
        trades: list[TradeRecord] = []

        opposite_book = self._ask_book if is_buy else self._bid_book
        same_book = self._bid_book if is_buy else self._ask_book

        while remaining > 0 and opposite_book.best_valid:
            opposite_best = opposite_book.best_price
            crosses = is_market or (
                opposite_best <= price if is_buy else opposite_best >= price
            )
            if not crosses:
                break

            response = opposite_book.consume(quantity=remaining)
            consumed = response.quantity
            if consumed == 0:
                break

            trades.append(TradeRecord(
                price=opposite_best,
                quantity=consumed,
                side=0 if is_buy else 1,
            ))
            remaining -= consumed
            self._total_trades += 1
            self._total_volume += consumed
            self._last_trade_price = opposite_best
            self._last_trade_price_valid = True

        if remaining > 0 and not is_market:
            same_book.insert(price=price, quantity=remaining)

        return trades

    def run_sequence(self, packets: list[int]) -> list[StepRecord]:
        """Processes a sequence of packets and records the full state after each step.

        Args:
            packets: The list of raw 32-bit order packets to replay.

        Returns:
            A list of StepRecord instances capturing per-packet trades and book state.
        """
        records: list[StepRecord] = []
        for step, packet in enumerate(packets):
            side, order_type, agent_type, price, volume = decode_packet(packet=packet)
            trades = self.process_packet(packet=packet)
            records.append(StepRecord(
                step=step,
                packet=packet,
                side=side,
                order_type=order_type,
                agent_type=agent_type,
                price=price,
                volume=volume,
                trades=trades,
                best_bid_price=self._bid_book.best_price,
                best_bid_quantity=self._bid_book.best_quantity,
                best_bid_valid=self._bid_book.best_valid,
                best_ask_price=self._ask_book.best_price,
                best_ask_quantity=self._ask_book.best_quantity,
                best_ask_valid=self._ask_book.best_valid,
                last_trade_price=self._last_trade_price,
                last_trade_price_valid=self._last_trade_price_valid,
                total_trades=self._total_trades,
                total_volume=self._total_volume,
            ))
        return records


def generate_deterministic_sweep(
    price_range: int = _DEFAULT_PRICE_RANGE,
    seed: int = _DEFAULT_SEED,
) -> list[int]:
    """Generates a deterministic packet sequence exercising all matching engine paths.

    Covers: seeding both sides with limit orders, aggregation at a shared price, non-crossing
    limits (pure insert), crossing limits (match then insert remainder), market orders that
    sweep multiple levels, market orders that exhaust the opposite side, and a market order
    against an empty opposite side.

    Args:
        price_range: The addressable tick range.
        seed: The random seed for reproducible sampling in the interleaved phase.

    Returns:
        A list of packed 32-bit order packets.
    """
    rng = random.Random(seed)
    packets: list[int] = []
    price_step = 20

    # Phase 1: seed the ask book with five ascending limits.
    for level_index in range(5):
        packets.append(encode_packet(
            side=1, order_type=0, agent_type=3,
            price=200 + level_index * price_step,
            volume=rng.randint(3, 8),
        ))

    # Phase 2: seed the bid book with five descending limits, well below the ask.
    for level_index in range(5):
        packets.append(encode_packet(
            side=0, order_type=0, agent_type=3,
            price=180 - level_index * price_step,
            volume=rng.randint(3, 8),
        ))

    # Phase 3: aggregate onto an existing bid level.
    packets.append(encode_packet(
        side=0, order_type=0, agent_type=3, price=180, volume=4,
    ))

    # Phase 4: crossing limit buy that takes part of the best ask and inserts the remainder.
    packets.append(encode_packet(
        side=0, order_type=0, agent_type=3, price=210, volume=20,
    ))

    # Phase 5: market buy that sweeps multiple ask levels.
    packets.append(encode_packet(
        side=0, order_type=1, agent_type=2, price=0, volume=15,
    ))

    # Phase 6: market sell that consumes the top bid.
    packets.append(encode_packet(
        side=1, order_type=1, agent_type=2, price=0, volume=3,
    ))

    # Phase 7: random interleaved activity. Coverage-oriented; not a stress test.
    for _ in range(50):
        choice = rng.random()
        if choice < 0.4:
            packets.append(encode_packet(
                side=rng.randint(0, 1), order_type=0, agent_type=rng.randint(0, 3),
                price=rng.randint(50, 400), volume=rng.randint(1, 6),
            ))
        elif choice < 0.7:
            packets.append(encode_packet(
                side=rng.randint(0, 1), order_type=1, agent_type=rng.randint(0, 3),
                price=0, volume=rng.randint(1, 5),
            ))
        else:
            packets.append(encode_packet(
                side=rng.randint(0, 1), order_type=0, agent_type=rng.randint(0, 3),
                price=rng.choice([200, 220, 240, 180, 160, 140]), volume=rng.randint(1, 5),
            ))

    # Phase 8: drain both sides with large market orders.
    for _ in range(4):
        packets.append(encode_packet(
            side=0, order_type=1, agent_type=2, price=0, volume=100,
        ))
        packets.append(encode_packet(
            side=1, order_type=1, agent_type=2, price=0, volume=100,
        ))

    # Phase 9: market order against the now-empty book.
    packets.append(encode_packet(
        side=0, order_type=1, agent_type=2, price=0, volume=10,
    ))

    return packets


def generate_edge_case_packets(price_range: int = _DEFAULT_PRICE_RANGE) -> list[int]:
    """Generates a small set of boundary and saturation packets for stress runs.

    Targets corners that random sampling rarely produces: minimum and maximum tick prices,
    out-of-range prices, single-share volumes, and aggregate-quantity saturation by stacking
    near-max-volume inserts at the same price.

    Args:
        price_range: The addressable tick range, used to compute boundary indices.

    Returns:
        A list of packed 32-bit order packets covering edge cases.
    """
    packets: list[int] = []

    # Boundary: insert at price 0 (lowest tick).
    packets.append(encode_packet(
        side=0, order_type=0, agent_type=0, price=0, volume=1,
    ))
    # Boundary: insert at the highest valid tick.
    packets.append(encode_packet(
        side=1, order_type=0, agent_type=0, price=price_range - 1, volume=1,
    ))
    # Out-of-range insert; engine should silently drop.
    packets.append(encode_packet(
        side=0, order_type=0, agent_type=0, price=price_range, volume=5,
    ))
    # Minimum volume.
    packets.append(encode_packet(
        side=0, order_type=0, agent_type=0, price=100, volume=1,
    ))
    # Saturation prep: three inserts of 30000 shares at price 200 (sum = 90000) but
    # level_quantity is 16-bit so it caps at 65535. Stresses the addition path.
    packets.append(encode_packet(
        side=0, order_type=0, agent_type=0, price=200, volume=30000,
    ))
    packets.append(encode_packet(
        side=0, order_type=0, agent_type=0, price=200, volume=30000,
    ))
    packets.append(encode_packet(
        side=0, order_type=0, agent_type=0, price=200, volume=30000,
    ))
    # Maximum 16-bit volume on a fresh ask level.
    packets.append(encode_packet(
        side=1, order_type=0, agent_type=0, price=300, volume=65535,
    ))
    # Market against an empty opposite side (no bid yet on this fresh price).
    packets.append(encode_packet(
        side=1, order_type=1, agent_type=2, price=0, volume=10,
    ))
    # Drain everything posted so the next stress packets see a clean book.
    packets.append(encode_packet(
        side=1, order_type=1, agent_type=2, price=0, volume=65535,
    ))
    packets.append(encode_packet(
        side=0, order_type=1, agent_type=2, price=0, volume=65535,
    ))
    return packets


def generate_stress_sweep(
    packet_count: int,
    seed: int = _DEFAULT_SEED,
    include_edge_cases: bool = False,
    price_range: int = _DEFAULT_PRICE_RANGE,
) -> list[int]:
    """Generates a large randomized packet sweep for stress testing.

    Each packet draws a uniform random side, order type, agent type, valid price tick, and
    volume. Optionally prepends a fixed set of boundary and saturation cases so a single run
    exercises both random coverage and known edge conditions.

    Args:
        packet_count: The number of random packets to emit (in addition to any edge cases).
        seed: The deterministic seed for reproducible random sampling.
        include_edge_cases: When True, prepends generate_edge_case_packets() output.
        price_range: The addressable tick range; random prices are bounded by this.

    Returns:
        A list of packed 32-bit order packets.
    """
    rng = random.Random(seed)
    packets: list[int] = []
    if include_edge_cases:
        packets.extend(generate_edge_case_packets(price_range=price_range))

    for _ in range(packet_count):
        packets.append(encode_packet(
            side=rng.randint(0, 1),
            order_type=rng.randint(0, 1),
            agent_type=rng.randint(0, 3),
            price=rng.randint(0, price_range - 1),
            volume=rng.randint(1, 200),
        ))
    return packets


def write_packets_csv(packets: list[int], file_path: Path) -> None:
    """Writes the raw 32-bit packet sequence to a CSV for the Verilog testbench."""
    with file_path.open(mode="w", newline="") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(["packet_hex"])
        for packet in packets:
            writer.writerow([f"{packet:08x}"])


def write_expected_csv(records: list[StepRecord], file_path: Path) -> None:
    """Writes the golden model's expected book state after each packet to a CSV."""
    fieldnames = [
        "step", "packet_hex",
        "side", "order_type", "agent_type", "price", "volume",
        "trade_count", "total_fill_quantity",
        "best_bid_price", "best_bid_quantity", "best_bid_valid",
        "best_ask_price", "best_ask_quantity", "best_ask_valid",
        "last_trade_price", "last_trade_price_valid",
        "total_trades", "total_volume",
    ]
    with file_path.open(mode="w", newline="") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()
        for record in records:
            writer.writerow({
                "step": record.step,
                "packet_hex": f"{record.packet:08x}",
                "side": record.side,
                "order_type": record.order_type,
                "agent_type": record.agent_type,
                "price": record.price,
                "volume": record.volume,
                "trade_count": len(record.trades),
                "total_fill_quantity": sum(trade.quantity for trade in record.trades),
                "best_bid_price": record.best_bid_price,
                "best_bid_quantity": record.best_bid_quantity,
                "best_bid_valid": int(record.best_bid_valid),
                "best_ask_price": record.best_ask_price,
                "best_ask_quantity": record.best_ask_quantity,
                "best_ask_valid": int(record.best_ask_valid),
                "last_trade_price": record.last_trade_price,
                "last_trade_price_valid": int(record.last_trade_price_valid),
                "total_trades": record.total_trades,
                "total_volume": record.total_volume,
            })


def write_trades_csv(records: list[StepRecord], file_path: Path) -> None:
    """Writes every trade emitted across the run to a CSV for trade-bus comparison."""
    with file_path.open(mode="w", newline="") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(["step", "trade_index", "trade_price", "trade_quantity", "trade_side"])
        for record in records:
            for trade_index, trade in enumerate(record.trades):
                writer.writerow([
                    record.step, trade_index, trade.price, trade.quantity, trade.side,
                ])


def verify_against_verilog(expected_path: Path, actual_path: Path) -> dict[str, int | bool]:
    """Compares golden model expectations against Verilog simulation CSV output.

    Args:
        expected_path: Path to the golden model expected output CSV.
        actual_path: Path to the Verilog simulation output CSV.

    Returns:
        A summary dictionary with total_steps, matches, mismatches, and pass status.
    """
    with expected_path.open(mode="r") as expected_file:
        expected_rows = list(csv.DictReader(expected_file))
    with actual_path.open(mode="r") as actual_file:
        actual_rows = list(csv.DictReader(actual_file))

    total = min(len(expected_rows), len(actual_rows))
    matches = 0
    mismatches = 0

    comparison_fields = [
        "trade_count", "total_fill_quantity",
        "best_bid_price", "best_bid_quantity", "best_bid_valid",
        "best_ask_price", "best_ask_quantity", "best_ask_valid",
        "last_trade_price", "last_trade_price_valid",
        "total_trades", "total_volume",
    ]

    diff_path = actual_path.parent / "matching_engine_diff.csv"
    with diff_path.open(mode="w", newline="") as diff_file:
        diff_writer = csv.writer(diff_file)
        diff_writer.writerow(["row", "packet_hex", "field", "expected", "actual"])

        for index in range(total):
            expected = expected_rows[index]
            actual = actual_rows[index]
            mismatched_fields = [
                field_name for field_name in comparison_fields
                if str(expected[field_name]) != str(actual[field_name])
            ]
            if not mismatched_fields:
                matches += 1
                continue
            mismatches += 1
            for field_name in mismatched_fields:
                console.warning(
                    message=(
                        f"Row {index} ({expected['packet_hex']}) {field_name}: "
                        f"expected={expected[field_name]}, actual={actual[field_name]}"
                    ),
                )
                diff_writer.writerow([
                    index, expected["packet_hex"], field_name,
                    expected[field_name], actual[field_name],
                ])

    if mismatches > 0:
        console.log(message=f"Detailed diff written to {diff_path}")
    if len(expected_rows) != len(actual_rows):
        console.warning(
            message=(
                f"Row count mismatch: expected={len(expected_rows)}, "
                f"actual={len(actual_rows)}"
            ),
        )

    return {
        "total_steps": total,
        "matches": matches,
        "mismatches": mismatches,
        "all_passed": mismatches == 0 and len(expected_rows) == len(actual_rows),
    }


@click.command()
@click.option("--verify", is_flag=True, default=False,
              help="Skip generation; diff existing expected vs actual CSVs.")
@click.option("--price-range", type=int, default=_DEFAULT_PRICE_RANGE, show_default=True,
              help="Number of addressable price ticks.")
@click.option("--stress", type=int, default=0, show_default=True,
              help="When >0, switch to stress mode and emit N back-to-back random packets "
                   "instead of the deterministic regression sweep.")
@click.option("--edge-cases", is_flag=True, default=False,
              help="In stress mode, prepend a small set of boundary and saturation packets.")
def main(verify: bool, price_range: int, stress: int, edge_cases: bool) -> None:
    """Generate CSVs or diff existing Verilog output against the golden model."""
    output_directory = Path(__file__).resolve().parent.parent / "sim"
    output_directory.mkdir(exist_ok=True)
    packets_path = output_directory / "matching_engine_packets.csv"
    expected_path = output_directory / "matching_engine_expected.csv"
    trades_path = output_directory / "matching_engine_trades_expected.csv"
    actual_path = output_directory / "matching_engine_actual.csv"

    if verify:
        console.log(message="Comparing matching_engine_expected.csv vs matching_engine_actual.csv")
        if not expected_path.exists():
            console.error(
                message="matching_engine_expected.csv not found. Run without --verify first.",
                error=FileNotFoundError,
            )
        if not actual_path.exists():
            console.error(
                message="matching_engine_actual.csv not found. Run the CSV testbench first.",
                error=FileNotFoundError,
            )
        summary = verify_against_verilog(expected_path=expected_path, actual_path=actual_path)
        console.log(
            message=(
                f"  Total: {summary['total_steps']} steps, "
                f"{summary['matches']} matches, {summary['mismatches']} mismatches"
            ),
        )
        if summary["all_passed"]:
            console.success(message="All rows match -- hardware matches the golden model.")
            sys.exit(0)
        console.error(
            message="Mismatches detected between hardware and golden model.", exit_code=0,
        )
        sys.exit(1)

    if stress > 0:
        console.log(
            message=(
                f"Generating stress sweep ({stress} back-to-back packets"
                f"{', with edge cases' if edge_cases else ''})..."
            ),
        )
        packets = generate_stress_sweep(
            packet_count=stress,
            seed=_DEFAULT_SEED,
            include_edge_cases=edge_cases,
            price_range=price_range,
        )
    else:
        console.log(message="Generating deterministic packet sweep...")
        packets = generate_deterministic_sweep(price_range=price_range, seed=_DEFAULT_SEED)
    console.log(message=f"  Generated {len(packets)} packets")

    console.log(message="Running golden model...")
    engine = MatchingEngine(price_range=price_range)
    records = engine.run_sequence(packets=packets)
    console.log(
        message=(
            f"  Processed {len(records)} steps, "
            f"{engine.total_trades} trades, {engine.total_volume} shares"
        ),
    )

    write_packets_csv(packets=packets, file_path=packets_path)
    write_expected_csv(records=records, file_path=expected_path)
    write_trades_csv(records=records, file_path=trades_path)
    console.success(message=f"Wrote {packets_path}")
    console.success(message=f"Wrote {expected_path}")
    console.success(message=f"Wrote {trades_path}")


if __name__ == "__main__":
    main()
