"""Provides a Python golden model for the matching_engine Verilog module.

Replays a stream of order packets (limit buy, limit sell, market buy, market sell, cancel)
against an internal bid/ask book pair, producing a CSV trace of trade executions and book state
for cross-verification against the Verilog testbench output.
"""

from __future__ import annotations

import csv
import random
import sys
from dataclasses import dataclass, field
from pathlib import Path

from ...utilities import console, LogLevel
from .price_level_store_golden import PriceLevelStore


# Order type codes matching the Verilog localparam encoding.
_TYPE_LIMIT_BUY: int = 1
_TYPE_LIMIT_SELL: int = 2
_TYPE_MARKET_BUY: int = 3
_TYPE_MARKET_SELL: int = 4
_TYPE_CANCEL: int = 5

_TYPE_NAMES: dict[int, str] = {
    1: "LIMIT_BUY",
    2: "LIMIT_SELL",
    3: "MARKET_BUY",
    4: "MARKET_SELL",
    5: "CANCEL",
}


@dataclass
class TradeRecord:
    """Captures a single trade execution.

    Attributes:
        aggressor_id: The aggressive (incoming) order's identifier.
        resting_id: The resting (book) order's identifier.
        price: The execution price (always the resting order's price).
        quantity: The number of shares traded.
    """

    aggressor_id: int
    """The aggressive (incoming) order's identifier."""
    resting_id: int
    """The resting (book) order's identifier."""
    price: int
    """The execution price (always the resting order's price)."""
    quantity: int
    """The number of shares traded."""


@dataclass
class StepRecord:
    """Captures the complete state after processing one order.

    Attributes:
        step: The order index in the input sequence.
        order_type: The order type code.
        order_id: The order's unique identifier.
        order_price: The order's limit price.
        order_quantity: The order's share count.
        trades: The list of trades generated by this order.
        best_bid_price: The best bid price after processing.
        best_bid_quantity: The aggregate quantity at the best bid.
        best_bid_valid: Determines whether the bid book is nonempty.
        best_ask_price: The best ask price after processing.
        best_ask_quantity: The aggregate quantity at the best ask.
        best_ask_valid: Determines whether the ask book is nonempty.
        total_trades: The cumulative trade count.
        total_volume: The cumulative shares traded.
    """

    step: int
    """The order index in the input sequence."""
    order_type: int
    """The order type code."""
    order_id: int
    """The order's unique identifier."""
    order_price: int
    """The order's limit price."""
    order_quantity: int
    """The order's share count."""
    trades: list[TradeRecord] = field(default_factory=list)
    """The list of trades generated by this order."""
    best_bid_price: int = 0
    """The best bid price after processing."""
    best_bid_quantity: int = 0
    """The aggregate quantity at the best bid."""
    best_bid_valid: bool = False
    """Determines whether the bid book is nonempty."""
    best_ask_price: int = 0
    """The best ask price after processing."""
    best_ask_quantity: int = 0
    """The aggregate quantity at the best ask."""
    best_ask_valid: bool = False
    """Determines whether the ask book is nonempty."""
    total_trades: int = 0
    """The cumulative trade count."""
    total_volume: int = 0
    """The cumulative shares traded."""


class MatchingEngine:
    """Replicates the matching_engine Verilog module's order processing logic.

    Maintains a bid book and an ask book, processes incoming orders by matching against the
    opposite side, and inserts unmatched remainders. Tracks trade executions and cumulative
    statistics identically to the hardware.

    Args:
        depth: The maximum number of price levels per book side.
        max_orders: The maximum number of individual orders per book side.

    Attributes:
        _bid_book: The bid-side price level store (descending sort).
        _ask_book: The ask-side price level store (ascending sort).
        _total_trades: The cumulative trade count.
        _total_volume: The cumulative shares traded.
    """

    def __init__(self, depth: int = 16, max_orders: int = 256) -> None:
        self._bid_book: PriceLevelStore = PriceLevelStore(
            depth=depth, max_orders=max_orders, is_bid=True,
        )
        self._ask_book: PriceLevelStore = PriceLevelStore(
            depth=depth, max_orders=max_orders, is_bid=False,
        )
        self._total_trades: int = 0
        self._total_volume: int = 0

    def __repr__(self) -> str:
        """Returns a string representation of the MatchingEngine instance."""
        return (
            f"MatchingEngine(total_trades={self._total_trades}, "
            f"total_volume={self._total_volume}, "
            f"bid_levels={len(self._bid_book._levels)}, "
            f"ask_levels={len(self._ask_book._levels)})"
        )

    def process_order(self, order_type: int, order_id: int, order_price: int,
                      order_quantity: int) -> list[TradeRecord]:
        """Processes a single order packet and returns any resulting trades.

        Implements the same matching logic as the Verilog FSM: checks the opposite book for
        matchable prices, consumes in a loop, then inserts any remainder.

        Args:
            order_type: The order type code (limit buy/sell, market buy/sell, cancel).
            order_id: The order's unique identifier.
            order_price: The order's limit price in ticks (ignored for market orders).
            order_quantity: The number of shares.

        Returns:
            A list of TradeRecord instances for each execution that occurred.
        """
        if order_type == _TYPE_CANCEL:
            self._bid_book.cancel(order_id=order_id)
            self._ask_book.cancel(order_id=order_id)
            return []

        is_buy = order_type in (_TYPE_LIMIT_BUY, _TYPE_MARKET_BUY)
        is_market = order_type in (_TYPE_MARKET_BUY, _TYPE_MARKET_SELL)
        remaining = order_quantity
        trades: list[TradeRecord] = []

        opposite_book = self._ask_book if is_buy else self._bid_book
        same_book = self._bid_book if is_buy else self._ask_book

        while remaining > 0 and opposite_book.best_valid:
            opposite_best = opposite_book.best_price

            # Checks whether the opposite best price is matchable
            if is_buy:
                matchable = is_market or (opposite_best <= order_price)
            else:
                matchable = is_market or (opposite_best >= order_price)

            if not matchable:
                break

            fill_quantity = min(remaining, opposite_book.best_quantity)
            fill_responses = opposite_book.consume(quantity=fill_quantity)
            actual_filled = sum(response.quantity for response in fill_responses)

            if actual_filled > 0:
                # Uses the last consumed order's id as the resting id (matches Verilog behavior)
                resting_id = fill_responses[-1].order_id
                trades.append(TradeRecord(
                    aggressor_id=order_id,
                    resting_id=resting_id,
                    price=opposite_best,
                    quantity=actual_filled,
                ))
                remaining -= actual_filled
                self._total_trades += 1
                self._total_volume += actual_filled
            else:
                break

        # Inserts unmatched remainder into the same-side book (skip for market orders)
        if remaining > 0 and not is_market:
            same_book.insert(price=order_price, quantity=remaining, order_id=order_id)

        return trades

    def run_sequence(self, orders: list[dict[str, int]]) -> list[StepRecord]:
        """Processes a sequence of orders and records the state after each step.

        Args:
            orders: The list of order dictionaries with keys: order_type, order_id, price, quantity.

        Returns:
            A list of StepRecord instances capturing trades and book state per order.
        """
        records: list[StepRecord] = []

        for step, order in enumerate(orders):
            order_type = order["order_type"]
            order_id = order["order_id"]
            order_price = order["price"]
            order_quantity = order["quantity"]

            trades = self.process_order(
                order_type=order_type, order_id=order_id,
                order_price=order_price, order_quantity=order_quantity,
            )

            records.append(StepRecord(
                step=step,
                order_type=order_type,
                order_id=order_id,
                order_price=order_price,
                order_quantity=order_quantity,
                trades=trades,
                best_bid_price=self._bid_book.best_price,
                best_bid_quantity=self._bid_book.best_quantity,
                best_bid_valid=self._bid_book.best_valid,
                best_ask_price=self._ask_book.best_price,
                best_ask_quantity=self._ask_book.best_quantity,
                best_ask_valid=self._ask_book.best_valid,
                total_trades=self._total_trades,
                total_volume=self._total_volume,
            ))

        return records


def generate_test_sequence(seed: int = 42) -> list[dict[str, int]]:
    """Generates a deterministic order sequence exercising all matching engine paths.

    Args:
        seed: The random seed for reproducible order generation.

    Returns:
        A list of order dictionaries with keys: order_type, order_id, price, quantity.
    """
    rng = random.Random(seed)
    orders: list[dict[str, int]] = []
    next_id = 1

    def add(order_type: int, price: int, quantity: int) -> int:
        nonlocal next_id
        orders.append({
            "order_type": order_type,
            "order_id": next_id,
            "price": price,
            "quantity": quantity,
        })
        current_id = next_id
        next_id += 1
        return current_id

    # Phase 1: Builds initial book with resting orders on both sides
    add(order_type=_TYPE_LIMIT_BUY, price=100, quantity=50)
    add(order_type=_TYPE_LIMIT_BUY, price=99, quantity=30)
    add(order_type=_TYPE_LIMIT_BUY, price=98, quantity=20)
    add(order_type=_TYPE_LIMIT_SELL, price=105, quantity=40)
    add(order_type=_TYPE_LIMIT_SELL, price=110, quantity=25)
    add(order_type=_TYPE_LIMIT_SELL, price=115, quantity=15)

    # Phase 2: Exact match (sell at best bid price)
    add(order_type=_TYPE_LIMIT_SELL, price=100, quantity=20)

    # Phase 3: Price improvement (sell below best bid)
    add(order_type=_TYPE_LIMIT_SELL, price=95, quantity=10)

    # Phase 4: Buy above best ask (trades at ask price)
    add(order_type=_TYPE_LIMIT_BUY, price=120, quantity=15)

    # Phase 5: No match (buy below best ask, sell above best bid)
    add(order_type=_TYPE_LIMIT_BUY, price=102, quantity=10)
    add(order_type=_TYPE_LIMIT_SELL, price=108, quantity=10)

    # Phase 6: Market orders
    add(order_type=_TYPE_MARKET_BUY, price=0, quantity=30)
    add(order_type=_TYPE_MARKET_SELL, price=0, quantity=15)

    # Phase 7: Multi-level sweep (large aggressive buy)
    add(order_type=_TYPE_LIMIT_BUY, price=200, quantity=100)

    # Phase 8: Cancel a resting order
    cancel_target = 2
    orders.append({
        "order_type": _TYPE_CANCEL,
        "order_id": cancel_target,
        "price": 0,
        "quantity": 0,
    })
    next_id += 1

    # Phase 9: Cancel nonexistent
    orders.append({
        "order_type": _TYPE_CANCEL,
        "order_id": 9999,
        "price": 0,
        "quantity": 0,
    })
    next_id += 1

    # Phase 10: Random interleaved orders
    for _ in range(20):
        action = rng.choice(["limit_buy", "limit_sell", "market_buy", "market_sell", "cancel"])

        if action == "limit_buy":
            add(order_type=_TYPE_LIMIT_BUY, price=rng.randint(90, 115), quantity=rng.randint(1, 40))
        elif action == "limit_sell":
            add(order_type=_TYPE_LIMIT_SELL, price=rng.randint(95, 120), quantity=rng.randint(1, 40))
        elif action == "market_buy":
            add(order_type=_TYPE_MARKET_BUY, price=0, quantity=rng.randint(1, 30))
        elif action == "market_sell":
            add(order_type=_TYPE_MARKET_SELL, price=0, quantity=rng.randint(1, 30))
        else:
            orders.append({
                "order_type": _TYPE_CANCEL,
                "order_id": rng.randint(1, next_id - 1),
                "price": 0,
                "quantity": 0,
            })
            next_id += 1

    return orders


def write_orders_csv(orders: list[dict[str, int]], file_path: Path) -> None:
    """Writes the order sequence to a CSV file for Verilog testbench consumption.

    Args:
        orders: The order sequence to write.
        file_path: The output CSV file path.
    """
    with open(file_path, "w", newline="") as csv_file:
        writer = csv.DictWriter(
            csv_file, fieldnames=["order_type", "order_id", "price", "quantity"],
        )
        writer.writeheader()
        for order in orders:
            writer.writerow(order)


def write_trades_csv(records: list[StepRecord], file_path: Path) -> None:
    """Writes all trade executions to a CSV file for Verilog output comparison.

    Args:
        records: The step records containing trade data.
        file_path: The output CSV file path.
    """
    fieldnames = [
        "step", "aggressor_id", "resting_id", "trade_price", "trade_quantity",
    ]
    with open(file_path, "w", newline="") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()
        for record in records:
            for trade in record.trades:
                writer.writerow({
                    "step": record.step,
                    "aggressor_id": trade.aggressor_id,
                    "resting_id": trade.resting_id,
                    "trade_price": trade.price,
                    "trade_quantity": trade.quantity,
                })


def write_book_state_csv(records: list[StepRecord], file_path: Path) -> None:
    """Writes the book state after each order to a CSV file.

    Args:
        records: The step records containing book state data.
        file_path: The output CSV file path.
    """
    fieldnames = [
        "step", "order_type", "order_id", "order_price", "order_quantity",
        "best_bid_price", "best_bid_quantity", "best_bid_valid",
        "best_ask_price", "best_ask_quantity", "best_ask_valid",
        "total_trades", "total_volume",
    ]
    with open(file_path, "w", newline="") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()
        for record in records:
            writer.writerow({
                "step": record.step,
                "order_type": record.order_type,
                "order_id": record.order_id,
                "order_price": record.order_price,
                "order_quantity": record.order_quantity,
                "best_bid_price": record.best_bid_price,
                "best_bid_quantity": record.best_bid_quantity,
                "best_bid_valid": int(record.best_bid_valid),
                "best_ask_price": record.best_ask_price,
                "best_ask_quantity": record.best_ask_quantity,
                "best_ask_valid": int(record.best_ask_valid),
                "total_trades": record.total_trades,
                "total_volume": record.total_volume,
            })


def verify_against_verilog(
    expected_trades_path: Path,
    actual_trades_path: Path,
    expected_book_state_path: Path,
    actual_book_state_path: Path,
) -> dict[str, int | bool]:
    """Compares golden model expectations against Verilog simulation CSV output.

    Diffs the trades CSV and the book-state CSV row-by-row, emitting a warning per mismatched
    field and writing detailed diff CSVs for offline inspection.

    Args:
        expected_trades_path: Path to the golden model expected trades CSV.
        actual_trades_path: Path to the Verilog simulation actual trades CSV.
        expected_book_state_path: Path to the golden model expected book-state CSV.
        actual_book_state_path: Path to the Verilog simulation actual book-state CSV.

    Returns:
        A summary dictionary with trade_matches, trade_mismatches, book_matches,
        book_mismatches, and all_passed.
    """
    trade_fields = ["aggressor_id", "resting_id", "trade_price", "trade_quantity"]
    book_fields = [
        "best_bid_price", "best_bid_quantity", "best_bid_valid",
        "best_ask_price", "best_ask_quantity", "best_ask_valid",
        "total_trades", "total_volume",
    ]

    trade_matches, trade_mismatches = _compare_csv(
        expected_path=expected_trades_path,
        actual_path=actual_trades_path,
        comparison_fields=trade_fields,
        diff_path=actual_trades_path.parent / "matching_engine_trades_diff.csv",
        label="trade",
    )
    book_matches, book_mismatches = _compare_csv(
        expected_path=expected_book_state_path,
        actual_path=actual_book_state_path,
        comparison_fields=book_fields,
        diff_path=actual_book_state_path.parent / "matching_engine_book_state_diff.csv",
        label="book",
    )

    return {
        "trade_matches": trade_matches,
        "trade_mismatches": trade_mismatches,
        "book_matches": book_matches,
        "book_mismatches": book_mismatches,
        "all_passed": trade_mismatches == 0 and book_mismatches == 0,
    }


def _compare_csv(
    expected_path: Path,
    actual_path: Path,
    comparison_fields: list[str],
    diff_path: Path,
    label: str,
) -> tuple[int, int]:
    """Compares two CSVs row-by-row on the specified fields and writes a diff CSV.

    Args:
        expected_path: Path to the expected CSV.
        actual_path: Path to the actual CSV.
        comparison_fields: The field names to compare on each row.
        diff_path: Path to the diff CSV that will be written.
        label: A short label for console output (such as "trade" or "book").

    Returns:
        A tuple of (match_count, mismatch_count).
    """
    with open(expected_path, "r") as expected_file:
        expected_rows = list(csv.DictReader(expected_file))
    with open(actual_path, "r") as actual_file:
        actual_rows = list(csv.DictReader(actual_file))

    total = min(len(expected_rows), len(actual_rows))
    matches = 0
    mismatches = 0

    with open(diff_path, "w", newline="") as diff_file:
        diff_writer = csv.writer(diff_file)
        diff_writer.writerow(["row", "field", "expected", "actual"])

        for index in range(total):
            expected = expected_rows[index]
            actual = actual_rows[index]
            mismatched_fields = [
                field_name for field_name in comparison_fields
                if str(expected[field_name]) != str(actual[field_name])
            ]

            if not mismatched_fields:
                matches += 1
                continue

            mismatches += 1
            console.warning(message=f"{label.capitalize()} row {index} mismatch:")
            for field_name in mismatched_fields:
                console.warning(
                    message=(
                        f"  {field_name}: expected={expected[field_name]}, "
                        f"actual={actual[field_name]}"
                    ),
                )
                diff_writer.writerow([
                    index, field_name, expected[field_name], actual[field_name],
                ])

    if len(expected_rows) != len(actual_rows):
        console.warning(
            message=(
                f"{label.capitalize()} row count mismatch: "
                f"expected={len(expected_rows)}, actual={len(actual_rows)}"
            ),
        )

    if mismatches > 0:
        console.log(message=f"  Detailed {label} diff written to {diff_path}")

    return matches, mismatches


if __name__ == "__main__":
    # CSVs are written to the sim/ directory so ModelSim and Python share the same location.
    output_directory = Path(__file__).resolve().parent.parent / "sim"
    output_directory.mkdir(exist_ok=True)

    orders_path = output_directory / "matching_engine_orders.csv"
    expected_trades_path = output_directory / "matching_engine_trades_expected.csv"
    expected_book_state_path = output_directory / "matching_engine_book_state_expected.csv"
    actual_trades_path = output_directory / "matching_engine_trades_actual.csv"
    actual_book_state_path = output_directory / "matching_engine_book_state_actual.csv"

    if len(sys.argv) > 1 and sys.argv[1] == "--verify":
        console.log(message="Comparing expected vs actual matching engine CSVs...")

        for required_path in (
            expected_trades_path, actual_trades_path,
            expected_book_state_path, actual_book_state_path,
        ):
            if not required_path.exists():
                message = (
                    f"Unable to verify matching engine output. The file {required_path.name} "
                    f"was not found in {output_directory}."
                )
                console.error(message=message, error=FileNotFoundError)

        summary = verify_against_verilog(
            expected_trades_path=expected_trades_path,
            actual_trades_path=actual_trades_path,
            expected_book_state_path=expected_book_state_path,
            actual_book_state_path=actual_book_state_path,
        )
        console.log(
            message=(
                f"  Trades: {summary['trade_matches']} matches, "
                f"{summary['trade_mismatches']} mismatches"
            ),
        )
        console.log(
            message=(
                f"  Book state: {summary['book_matches']} matches, "
                f"{summary['book_mismatches']} mismatches"
            ),
        )

        if summary["all_passed"]:
            console.success(message="All rows match. The hardware matches the golden model.")
            sys.exit(0)
        else:
            console.error(
                message="Mismatches detected between hardware and golden model.", exit_code=0,
            )
            sys.exit(1)

    # Default mode: generate CSVs
    console.log(message="Generating test order sequence...")
    orders = generate_test_sequence(seed=42)
    console.log(message=f"  Generated {len(orders)} orders")

    console.log(message="Running matching engine golden model...")
    engine = MatchingEngine(depth=8, max_orders=16)
    records = engine.run_sequence(orders=orders)

    total_trade_count = sum(len(record.trades) for record in records)
    console.log(message=f"  Processed {len(records)} orders, {total_trade_count} trades")

    write_orders_csv(orders=orders, file_path=orders_path)
    write_trades_csv(records=records, file_path=expected_trades_path)
    write_book_state_csv(records=records, file_path=expected_book_state_path)

    console.success(message=f"Wrote {orders_path}")
    console.success(message=f"Wrote {expected_trades_path}")
    console.success(message=f"Wrote {expected_book_state_path}")

    # Prints a trace summary
    console.log("Trade trace:", level=LogLevel.DEBUG)
    for record in records:
        type_name = _TYPE_NAMES.get(record.order_type, "???")
        for trade in record.trades:
            console.log(
                f"  [{record.step:3d}] {type_name:12s} id={record.order_id:3d} -> "
                f"trade: aggressor={trade.aggressor_id} resting={trade.resting_id} "
                f"price={trade.price} qty={trade.quantity}",
                level=LogLevel.DEBUG,
            )

    console.log(f"\nFinal state: {engine}")
    console.log(
        f"  Best bid: {engine._bid_book.best_price} "
        f"(qty={engine._bid_book.best_quantity}, valid={engine._bid_book.best_valid})"
    )
    console.log(
        f"  Best ask: {engine._ask_book.best_price} "
        f"(qty={engine._ask_book.best_quantity}, valid={engine._ask_book.best_valid})"
    )

    # Self-verification: crossed book check
    if engine._bid_book.best_valid and engine._ask_book.best_valid:
        if engine._bid_book.best_price >= engine._ask_book.best_price:
            message = (
                f"Crossed book detected: best_bid={engine._bid_book.best_price} >= "
                f"best_ask={engine._ask_book.best_price}."
            )
            console.error(message=message, error=RuntimeError)
        else:
            console.success("Book invariant: best_bid < best_ask")
    else:
        console.success("Book invariant: at least one side empty (no crossing possible)")
